# SPDX-License-Identifier: MIT
---
- name: snapshot role invocation
  hosts: all
  vars:
    snapshot_percent_to_require: 20
    volumes: rhel, vg1, vg2, vg3
  roles:
    - linux-system-roles.snapshot

  tasks:
    - name: Snapshot System
      import_role:
        name: linux-system-roles.snapshot
