# SPDX-License-Identifier: MIT
---
- name: Example snapshot role invocation
  hosts: all
  vars:
    snapshot_system: true
    exclude_swap: true
    snapshot_space_avail_percent: 20
  roles:
    - linux-system-roles.snapshot
