- name: Verify that there is enough storage space
  ansible.builtin.script: snapshot.py check -a -r 20 -p a__ -s z__
  args:
    executable: "{{ ansible_python.executable }}"
  register: lvm_snapshots_check_space
  failed_when: false
  changed_when: false
